project_name: tech-bench-cli
builds:
  - dir: ./tech-bench-cli
    id: "tech-bench-cli"
    binary: tech-bench-cli
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
