project_name: tech-bench
builds:
  - main: ./cli
    id: "tech-bench"
    binary: tech-bench
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
